/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTagsIndexRouteImport } from './routes/dashboard/tags/index'
import { Route as DashboardPeopleIndexRouteImport } from './routes/dashboard/people/index'
import { Route as DashboardOrgsIndexRouteImport } from './routes/dashboard/orgs/index'
import { Route as DashboardEventsNewRouteImport } from './routes/dashboard/events/new'
import { Route as DashboardEventsEditRouteImport } from './routes/dashboard/events/edit'
import { Route as DashboardEventsEventIdRouteImport } from './routes/dashboard/events/$eventId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTagsIndexRoute = DashboardTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPeopleIndexRoute = DashboardPeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrgsIndexRoute = DashboardOrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsNewRoute = DashboardEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsEditRoute = DashboardEventsEditRouteImport.update({
  id: '/events/edit',
  path: '/events/edit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsEventIdRoute = DashboardEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/events/$eventId': typeof DashboardEventsEventIdRoute
  '/dashboard/events/edit': typeof DashboardEventsEditRoute
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/dashboard/orgs': typeof DashboardOrgsIndexRoute
  '/dashboard/people': typeof DashboardPeopleIndexRoute
  '/dashboard/tags': typeof DashboardTagsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/events/$eventId': typeof DashboardEventsEventIdRoute
  '/dashboard/events/edit': typeof DashboardEventsEditRoute
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/dashboard/orgs': typeof DashboardOrgsIndexRoute
  '/dashboard/people': typeof DashboardPeopleIndexRoute
  '/dashboard/tags': typeof DashboardTagsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/events/$eventId': typeof DashboardEventsEventIdRoute
  '/dashboard/events/edit': typeof DashboardEventsEditRoute
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/dashboard/orgs/': typeof DashboardOrgsIndexRoute
  '/dashboard/people/': typeof DashboardPeopleIndexRoute
  '/dashboard/tags/': typeof DashboardTagsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/events/$eventId'
    | '/dashboard/events/edit'
    | '/dashboard/events/new'
    | '/dashboard/orgs'
    | '/dashboard/people'
    | '/dashboard/tags'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/events/$eventId'
    | '/dashboard/events/edit'
    | '/dashboard/events/new'
    | '/dashboard/orgs'
    | '/dashboard/people'
    | '/dashboard/tags'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/events/$eventId'
    | '/dashboard/events/edit'
    | '/dashboard/events/new'
    | '/dashboard/orgs/'
    | '/dashboard/people/'
    | '/dashboard/tags/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tags/': {
      id: '/dashboard/tags/'
      path: '/tags'
      fullPath: '/dashboard/tags'
      preLoaderRoute: typeof DashboardTagsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/people/': {
      id: '/dashboard/people/'
      path: '/people'
      fullPath: '/dashboard/people'
      preLoaderRoute: typeof DashboardPeopleIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orgs/': {
      id: '/dashboard/orgs/'
      path: '/orgs'
      fullPath: '/dashboard/orgs'
      preLoaderRoute: typeof DashboardOrgsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events/new': {
      id: '/dashboard/events/new'
      path: '/events/new'
      fullPath: '/dashboard/events/new'
      preLoaderRoute: typeof DashboardEventsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events/edit': {
      id: '/dashboard/events/edit'
      path: '/events/edit'
      fullPath: '/dashboard/events/edit'
      preLoaderRoute: typeof DashboardEventsEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events/$eventId': {
      id: '/dashboard/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/dashboard/events/$eventId'
      preLoaderRoute: typeof DashboardEventsEventIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardEventsEventIdRoute: typeof DashboardEventsEventIdRoute
  DashboardEventsEditRoute: typeof DashboardEventsEditRoute
  DashboardEventsNewRoute: typeof DashboardEventsNewRoute
  DashboardOrgsIndexRoute: typeof DashboardOrgsIndexRoute
  DashboardPeopleIndexRoute: typeof DashboardPeopleIndexRoute
  DashboardTagsIndexRoute: typeof DashboardTagsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardEventsEventIdRoute: DashboardEventsEventIdRoute,
  DashboardEventsEditRoute: DashboardEventsEditRoute,
  DashboardEventsNewRoute: DashboardEventsNewRoute,
  DashboardOrgsIndexRoute: DashboardOrgsIndexRoute,
  DashboardPeopleIndexRoute: DashboardPeopleIndexRoute,
  DashboardTagsIndexRoute: DashboardTagsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
