/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardWipIndexRouteImport } from './routes/dashboard/wip/index'
import { Route as DashboardTransactionsIndexRouteImport } from './routes/dashboard/transactions/index'
import { Route as DashboardTagsIndexRouteImport } from './routes/dashboard/tags/index'
import { Route as DashboardStudentsIndexRouteImport } from './routes/dashboard/students/index'
import { Route as DashboardRevenueIndexRouteImport } from './routes/dashboard/revenue/index'
import { Route as DashboardPeopleIndexRouteImport } from './routes/dashboard/people/index'
import { Route as DashboardParticipantsIndexRouteImport } from './routes/dashboard/participants/index'
import { Route as DashboardOrgsIndexRouteImport } from './routes/dashboard/orgs/index'
import { Route as DashboardEventsIndexRouteImport } from './routes/dashboard/events/index'
import { Route as DashboardRevenueTransactionsRouteImport } from './routes/dashboard/revenue/transactions'
import { Route as DashboardEventsEventIdRouteImport } from './routes/dashboard/events/$eventId'

const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWipIndexRoute = DashboardWipIndexRouteImport.update({
  id: '/wip/',
  path: '/wip/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTransactionsIndexRoute =
  DashboardTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardTagsIndexRoute = DashboardTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudentsIndexRoute = DashboardStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRevenueIndexRoute = DashboardRevenueIndexRouteImport.update({
  id: '/revenue/',
  path: '/revenue/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPeopleIndexRoute = DashboardPeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardParticipantsIndexRoute =
  DashboardParticipantsIndexRouteImport.update({
    id: '/participants/',
    path: '/participants/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardOrgsIndexRoute = DashboardOrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsIndexRoute = DashboardEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRevenueTransactionsRoute =
  DashboardRevenueTransactionsRouteImport.update({
    id: '/revenue/transactions',
    path: '/revenue/transactions',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardEventsEventIdRoute = DashboardEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/maintenance': typeof MaintenanceRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/events/$eventId': typeof DashboardEventsEventIdRoute
  '/dashboard/revenue/transactions': typeof DashboardRevenueTransactionsRoute
  '/dashboard/events': typeof DashboardEventsIndexRoute
  '/dashboard/orgs': typeof DashboardOrgsIndexRoute
  '/dashboard/participants': typeof DashboardParticipantsIndexRoute
  '/dashboard/people': typeof DashboardPeopleIndexRoute
  '/dashboard/revenue': typeof DashboardRevenueIndexRoute
  '/dashboard/students': typeof DashboardStudentsIndexRoute
  '/dashboard/tags': typeof DashboardTagsIndexRoute
  '/dashboard/transactions': typeof DashboardTransactionsIndexRoute
  '/dashboard/wip': typeof DashboardWipIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/maintenance': typeof MaintenanceRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/events/$eventId': typeof DashboardEventsEventIdRoute
  '/dashboard/revenue/transactions': typeof DashboardRevenueTransactionsRoute
  '/dashboard/events': typeof DashboardEventsIndexRoute
  '/dashboard/orgs': typeof DashboardOrgsIndexRoute
  '/dashboard/participants': typeof DashboardParticipantsIndexRoute
  '/dashboard/people': typeof DashboardPeopleIndexRoute
  '/dashboard/revenue': typeof DashboardRevenueIndexRoute
  '/dashboard/students': typeof DashboardStudentsIndexRoute
  '/dashboard/tags': typeof DashboardTagsIndexRoute
  '/dashboard/transactions': typeof DashboardTransactionsIndexRoute
  '/dashboard/wip': typeof DashboardWipIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/maintenance': typeof MaintenanceRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/events/$eventId': typeof DashboardEventsEventIdRoute
  '/dashboard/revenue/transactions': typeof DashboardRevenueTransactionsRoute
  '/dashboard/events/': typeof DashboardEventsIndexRoute
  '/dashboard/orgs/': typeof DashboardOrgsIndexRoute
  '/dashboard/participants/': typeof DashboardParticipantsIndexRoute
  '/dashboard/people/': typeof DashboardPeopleIndexRoute
  '/dashboard/revenue/': typeof DashboardRevenueIndexRoute
  '/dashboard/students/': typeof DashboardStudentsIndexRoute
  '/dashboard/tags/': typeof DashboardTagsIndexRoute
  '/dashboard/transactions/': typeof DashboardTransactionsIndexRoute
  '/dashboard/wip/': typeof DashboardWipIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/maintenance'
    | '/dashboard/'
    | '/dashboard/events/$eventId'
    | '/dashboard/revenue/transactions'
    | '/dashboard/events'
    | '/dashboard/orgs'
    | '/dashboard/participants'
    | '/dashboard/people'
    | '/dashboard/revenue'
    | '/dashboard/students'
    | '/dashboard/tags'
    | '/dashboard/transactions'
    | '/dashboard/wip'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/maintenance'
    | '/dashboard'
    | '/dashboard/events/$eventId'
    | '/dashboard/revenue/transactions'
    | '/dashboard/events'
    | '/dashboard/orgs'
    | '/dashboard/participants'
    | '/dashboard/people'
    | '/dashboard/revenue'
    | '/dashboard/students'
    | '/dashboard/tags'
    | '/dashboard/transactions'
    | '/dashboard/wip'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/maintenance'
    | '/dashboard/'
    | '/dashboard/events/$eventId'
    | '/dashboard/revenue/transactions'
    | '/dashboard/events/'
    | '/dashboard/orgs/'
    | '/dashboard/participants/'
    | '/dashboard/people/'
    | '/dashboard/revenue/'
    | '/dashboard/students/'
    | '/dashboard/tags/'
    | '/dashboard/transactions/'
    | '/dashboard/wip/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  MaintenanceRoute: typeof MaintenanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/wip/': {
      id: '/dashboard/wip/'
      path: '/wip'
      fullPath: '/dashboard/wip'
      preLoaderRoute: typeof DashboardWipIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/transactions/': {
      id: '/dashboard/transactions/'
      path: '/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof DashboardTransactionsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tags/': {
      id: '/dashboard/tags/'
      path: '/tags'
      fullPath: '/dashboard/tags'
      preLoaderRoute: typeof DashboardTagsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/students/': {
      id: '/dashboard/students/'
      path: '/students'
      fullPath: '/dashboard/students'
      preLoaderRoute: typeof DashboardStudentsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/revenue/': {
      id: '/dashboard/revenue/'
      path: '/revenue'
      fullPath: '/dashboard/revenue'
      preLoaderRoute: typeof DashboardRevenueIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/people/': {
      id: '/dashboard/people/'
      path: '/people'
      fullPath: '/dashboard/people'
      preLoaderRoute: typeof DashboardPeopleIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/participants/': {
      id: '/dashboard/participants/'
      path: '/participants'
      fullPath: '/dashboard/participants'
      preLoaderRoute: typeof DashboardParticipantsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orgs/': {
      id: '/dashboard/orgs/'
      path: '/orgs'
      fullPath: '/dashboard/orgs'
      preLoaderRoute: typeof DashboardOrgsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events/': {
      id: '/dashboard/events/'
      path: '/events'
      fullPath: '/dashboard/events'
      preLoaderRoute: typeof DashboardEventsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/revenue/transactions': {
      id: '/dashboard/revenue/transactions'
      path: '/revenue/transactions'
      fullPath: '/dashboard/revenue/transactions'
      preLoaderRoute: typeof DashboardRevenueTransactionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events/$eventId': {
      id: '/dashboard/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/dashboard/events/$eventId'
      preLoaderRoute: typeof DashboardEventsEventIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardEventsEventIdRoute: typeof DashboardEventsEventIdRoute
  DashboardRevenueTransactionsRoute: typeof DashboardRevenueTransactionsRoute
  DashboardEventsIndexRoute: typeof DashboardEventsIndexRoute
  DashboardOrgsIndexRoute: typeof DashboardOrgsIndexRoute
  DashboardParticipantsIndexRoute: typeof DashboardParticipantsIndexRoute
  DashboardPeopleIndexRoute: typeof DashboardPeopleIndexRoute
  DashboardRevenueIndexRoute: typeof DashboardRevenueIndexRoute
  DashboardStudentsIndexRoute: typeof DashboardStudentsIndexRoute
  DashboardTagsIndexRoute: typeof DashboardTagsIndexRoute
  DashboardTransactionsIndexRoute: typeof DashboardTransactionsIndexRoute
  DashboardWipIndexRoute: typeof DashboardWipIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardEventsEventIdRoute: DashboardEventsEventIdRoute,
  DashboardRevenueTransactionsRoute: DashboardRevenueTransactionsRoute,
  DashboardEventsIndexRoute: DashboardEventsIndexRoute,
  DashboardOrgsIndexRoute: DashboardOrgsIndexRoute,
  DashboardParticipantsIndexRoute: DashboardParticipantsIndexRoute,
  DashboardPeopleIndexRoute: DashboardPeopleIndexRoute,
  DashboardRevenueIndexRoute: DashboardRevenueIndexRoute,
  DashboardStudentsIndexRoute: DashboardStudentsIndexRoute,
  DashboardTagsIndexRoute: DashboardTagsIndexRoute,
  DashboardTransactionsIndexRoute: DashboardTransactionsIndexRoute,
  DashboardWipIndexRoute: DashboardWipIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  MaintenanceRoute: MaintenanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
